name: Monday Dental Lead Gen

on:
  schedule:
    # 0 mins, 9 hours (9 AM UTC), * any day, * any month, 1 (Monday)
    - cron: '0 9 * * 1'
  workflow_dispatch: # This adds a "Run" button so you can test it NOW

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas google-search-results

      - name: Run Script
        env:
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
        run: python main.py

      - name: Save Results
        uses: actions/upload-artifact@v4
        with:
          name: dental-leads-list
          path: monday_leads.csv
